//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FO3ProfileManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FO3ProfileManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SLocalSavePath=.
        /// </summary>
        internal static string ConfigKey {
            get {
                return ResourceManager.GetString("ConfigKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fose_loader.exe.
        /// </summary>
        internal static string DefaultExe {
            get {
                return ResourceManager.GetString("DefaultExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \My Games\Fallout3\Fallout.ini.
        /// </summary>
        internal static string Fallout3DotIniPath {
            get {
                return ResourceManager.GetString("Fallout3DotIniPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \My Games\Fallout3\.
        /// </summary>
        internal static string Fallout3Path {
            get {
                return ResourceManager.GetString("Fallout3Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a profile first. If there is none, then you may click the Action menu and create a new one or generate it/them from your saved games.
        /// </summary>
        internal static string NoProfileSelected {
            get {
                return ResourceManager.GetString("NoProfileSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t create profile, there&apos;s already a folder with that name in your saves directory..
        /// </summary>
        internal static string ProfileExists {
            get {
                return ResourceManager.GetString("ProfileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t read from registry, please set the path to the game exe..
        /// </summary>
        internal static string RegistryError {
            get {
                return ResourceManager.GetString("RegistryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed Path.
        /// </summary>
        internal static string RegistryKey {
            get {
                return ResourceManager.GetString("RegistryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\Wow6432Node\Bethesda Softworks\Fallout3\.
        /// </summary>
        internal static string RegistryPath {
            get {
                return ResourceManager.GetString("RegistryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Games\Fallout3\Saves\.
        /// </summary>
        internal static string RootSavesFullPath {
            get {
                return ResourceManager.GetString("RootSavesFullPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves\.
        /// </summary>
        internal static string RootSavesSubPath {
            get {
                return ResourceManager.GetString("RootSavesSubPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FO3ProfileManager.xml.
        /// </summary>
        internal static string SettingsFileName {
            get {
                return ResourceManager.GetString("SettingsFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ThumbsUp {
            get {
                object obj = ResourceManager.GetObject("ThumbsUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
